---
- name: Include distribution specific vagrant tasks
  include: "vagrant-{{ ansible_os_family }}.yml"
  tags: vagrant

- name: Include vagrant tasks
  include: vagrant.yml
  tags: vagrant

- name: Include distribution specific virtualbox tasks
  include: "virtualbox-{{ ansible_os_family }}.yml"
  tags: virtualbox
