# This file is subject to the terms and conditions defined in file 'LICENSE',
# which is part of this repository.
---
- name: Add virtualbox repository
  apt_repository:
    repo: "deb http://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib"
    state: present
  become: true

- name: Add virtualbox repository gpg key
  apt_key:
    url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
    state: present
  become: true

- name: Install virtualbox
  package:
    name: virtualbox
    state: present
  become: true
